// Package postgres is the persistent MessageStore, backed by pgx.
//
// Apply internal/store/postgres/schema.sql before first use — this package
// does not create its own tables.
package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/harryemmett/harrys-project/messages-service/internal/domain"
	"github.com/harryemmett/harrys-project/messages-service/internal/store"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store implements store.MessageStore against Postgres.
type Store struct {
	pool *pgxpool.Pool
}

var _ store.MessageStore = (*Store)(nil)

// New connects to the given DSN and verifies the connection before returning,
// so a bad database config fails at boot rather than on the first request.
func New(ctx context.Context, dsn string) (*Store, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("postgres: connect: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("postgres: ping: %w", err)
	}
	return &Store{pool: pool}, nil
}

const selectColumns = `id, conversation_id, sender_id, content, sent_at`

// ListByConversation returns up to page.Limit messages, newest first.
func (s *Store) ListByConversation(ctx context.Context, conversationID string, page store.Page) ([]domain.Message, error) {
	page = page.Normalise()

	// A single query handles both the first page and the cursor case: when
	// Before is the zero time, the $2 predicate is switched off by $3.
	const q = `
		SELECT ` + selectColumns + `
		FROM messages
		WHERE conversation_id = $1
		  AND ($3 = false OR sent_at < $2)
		ORDER BY sent_at DESC, id DESC
		LIMIT $4`

	rows, err := s.pool.Query(ctx, q, conversationID, page.Before, !page.Before.IsZero(), page.Limit)
	if err != nil {
		return nil, fmt.Errorf("postgres: list messages: %w", err)
	}
	defer rows.Close()

	out := make([]domain.Message, 0, page.Limit)
	for rows.Next() {
		var m domain.Message
		if err := rows.Scan(&m.ID, &m.ConversationID, &m.SenderID, &m.Content, &m.SentAt); err != nil {
			return nil, fmt.Errorf("postgres: scan message: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("postgres: list messages: %w", err)
	}
	return out, nil
}

// Get returns one message by id.
func (s *Store) Get(ctx context.Context, id string) (domain.Message, error) {
	const q = `SELECT ` + selectColumns + ` FROM messages WHERE id = $1`

	var out domain.Message
	err := s.pool.QueryRow(ctx, q, id).
		Scan(&out.ID, &out.ConversationID, &out.SenderID, &out.Content, &out.SentAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Message{}, domain.ErrNotFound
	}
	if err != nil {
		return domain.Message{}, fmt.Errorf("postgres: get message: %w", err)
	}
	return out, nil
}

// Create inserts a message. The id and timestamp are generated by the domain
// layer, not by column defaults, so both stores behave identically.
func (s *Store) Create(ctx context.Context, msg domain.Message) (domain.Message, error) {
	const q = `
		INSERT INTO messages (id, conversation_id, sender_id, content, sent_at)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING ` + selectColumns

	var out domain.Message
	err := s.pool.QueryRow(ctx, q, msg.ID, msg.ConversationID, msg.SenderID, msg.Content, msg.SentAt).
		Scan(&out.ID, &out.ConversationID, &out.SenderID, &out.Content, &out.SentAt)
	if err != nil {
		return domain.Message{}, fmt.Errorf("postgres: create message: %w", err)
	}
	return out, nil
}

// Update replaces a message's content.
func (s *Store) Update(ctx context.Context, id, content string) (domain.Message, error) {
	const q = `
		UPDATE messages
		SET content = $2
		WHERE id = $1
		RETURNING ` + selectColumns

	var out domain.Message
	err := s.pool.QueryRow(ctx, q, id, content).
		Scan(&out.ID, &out.ConversationID, &out.SenderID, &out.Content, &out.SentAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Message{}, domain.ErrNotFound
	}
	if err != nil {
		return domain.Message{}, fmt.Errorf("postgres: update message: %w", err)
	}
	return out, nil
}

// Delete removes a message.
func (s *Store) Delete(ctx context.Context, id string) error {
	tag, err := s.pool.Exec(ctx, `DELETE FROM messages WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("postgres: delete message: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return domain.ErrNotFound
	}
	return nil
}

// Close releases the connection pool.
func (s *Store) Close() { s.pool.Close() }
